-- Vistas de nomina (snapshot de produccion, sincronizado al repo)
-- Empleados/trabajadores y pensionados. Sin DEFINER. Idempotente.

-- ============ v_planillas_trabajadores ============
CREATE OR REPLACE VIEW v_planillas_trabajadores AS
select `p`.`ppl_correlativo` AS `id_planilla`,`p`.`ppl_numero` AS `periodo`,`p`.`ppl_fecha_inicio` AS `ppl_fecha_inicio`,`p`.`ppl_fecha_final` AS `ppl_fecha_final`,`p`.`ppl_fecha_pago` AS `ppl_fecha_pago`,`p`.`ppl_porcentaje_pago` AS `porcentaje`,`p`.`ppl_estado_proceso` AS `estado`,`p`.`ppl_fecha_generacion` AS `ppl_fecha_generacion`,`p`.`ppl_fecha_cierre` AS `ppl_fecha_cierre`,`p`.`ppl_usuario_genera` AS `ppl_usuario_genera`,`p`.`ppl_usuario_cierra` AS `ppl_usuario_cierra`,(select count(distinct `apps_rpjepq`.`rpj_prc_nomina_ingreso`.`nin_id_empleado`) from `apps_rpjepq`.`rpj_prc_nomina_ingreso` where `apps_rpjepq`.`rpj_prc_nomina_ingreso`.`nin_id_planilla` = `p`.`ppl_correlativo` and `apps_rpjepq`.`rpj_prc_nomina_ingreso`.`nin_tipo_manejo` = 1) AS `total_empleados`,(select ifnull(sum(`apps_rpjepq`.`rpj_prc_nomina_ingreso`.`nin_valor`),0) from `apps_rpjepq`.`rpj_prc_nomina_ingreso` where `apps_rpjepq`.`rpj_prc_nomina_ingreso`.`nin_id_planilla` = `p`.`ppl_correlativo` and `apps_rpjepq`.`rpj_prc_nomina_ingreso`.`nin_tipo_manejo` = 1) AS `total_ingresos`,(select ifnull(sum(`apps_rpjepq`.`rpj_prc_nomina_descuento`.`nde_valor`),0) from `apps_rpjepq`.`rpj_prc_nomina_descuento` where `apps_rpjepq`.`rpj_prc_nomina_descuento`.`nde_id_planilla` = `p`.`ppl_correlativo` and `apps_rpjepq`.`rpj_prc_nomina_descuento`.`nde_tipo_manejo` = 1) AS `total_descuentos` from `apps_rpjepq`.`rpj_cat_parametro_planilla` `p` where `p`.`ppl_aplica_porcentaje` = 0 or `p`.`ppl_tipo_planilla` in (select `apps_rpjepq`.`rpj_cat_tipo_planilla`.`tpl_id` from `apps_rpjepq`.`rpj_cat_tipo_planilla` where `apps_rpjepq`.`rpj_cat_tipo_planilla`.`tpl_id_tipo_uso` = 'TRABAJADORES') order by `p`.`ppl_numero` desc;

-- ============ v_detalle_nomina_trabajadores ============
CREATE OR REPLACE VIEW v_detalle_nomina_trabajadores AS
select `ni`.`nin_id_planilla` AS `nin_id_planilla`,`p`.`ppl_numero` AS `planilla`,`p`.`ppl_estado_proceso` AS `estado_planilla`,`e`.`emp_correlativo` AS `id_empleado`,`e`.`emp_dpi` AS `emp_dpi`,concat(`e`.`emp_nombres`,' ',`e`.`emp_apellidos`) AS `nombre_completo`,`e`.`emp_fecha_ingreso` AS `emp_fecha_ingreso`,`e`.`emp_profesion_oficio` AS `puesto`,`ti`.`tin_tipo_ingreso` AS `tipo_ingreso`,`ni`.`nin_valor_teorico` AS `salario_teorico`,`ni`.`nin_porcentaje_aplicado` AS `porcentaje`,`ni`.`nin_dias_trabajados` AS `dias_trabajados`,`ni`.`nin_valor` AS `valor_ingreso` from (((`apps_rpjepq`.`rpj_prc_nomina_ingreso` `ni` join `apps_rpjepq`.`rpj_cat_parametro_planilla` `p` on(`p`.`ppl_correlativo` = `ni`.`nin_id_planilla`)) join `apps_rpjepq`.`rpj_mnt_empleado` `e` on(`e`.`emp_correlativo` = `ni`.`nin_id_empleado`)) join `apps_rpjepq`.`rpj_cat_tipo_ingreso` `ti` on(`ti`.`tin_id` = `ni`.`nin_tipo_ingreso`)) where `ni`.`nin_tipo_manejo` = 1;

-- ============ v_neto_pagar_trabajadores ============
CREATE OR REPLACE VIEW v_neto_pagar_trabajadores AS
select `ni`.`nin_id_planilla` AS `nin_id_planilla`,`p`.`ppl_numero` AS `planilla`,`p`.`ppl_estado_proceso` AS `estado_planilla`,`e`.`emp_correlativo` AS `id_empleado`,`e`.`emp_dpi` AS `emp_dpi`,concat(`e`.`emp_nombres`,' ',`e`.`emp_apellidos`) AS `nombre_completo`,`e`.`emp_fecha_ingreso` AS `emp_fecha_ingreso`,`e`.`emp_profesion_oficio` AS `puesto`,`ni`.`nin_dias_trabajados` AS `dias_trabajados`,sum(`ni`.`nin_valor`) AS `total_ingresos`,coalesce((select sum(`apps_rpjepq`.`rpj_prc_nomina_descuento`.`nde_valor`) from `apps_rpjepq`.`rpj_prc_nomina_descuento` where `apps_rpjepq`.`rpj_prc_nomina_descuento`.`nde_id_planilla` = `ni`.`nin_id_planilla` and `apps_rpjepq`.`rpj_prc_nomina_descuento`.`nde_id_empleado` = `ni`.`nin_id_empleado`),0) AS `total_descuentos`,sum(`ni`.`nin_valor`) - coalesce((select sum(`apps_rpjepq`.`rpj_prc_nomina_descuento`.`nde_valor`) from `apps_rpjepq`.`rpj_prc_nomina_descuento` where `apps_rpjepq`.`rpj_prc_nomina_descuento`.`nde_id_planilla` = `ni`.`nin_id_planilla` and `apps_rpjepq`.`rpj_prc_nomina_descuento`.`nde_id_empleado` = `ni`.`nin_id_empleado`),0) AS `neto_a_pagar` from ((`apps_rpjepq`.`rpj_prc_nomina_ingreso` `ni` join `apps_rpjepq`.`rpj_cat_parametro_planilla` `p` on(`p`.`ppl_correlativo` = `ni`.`nin_id_planilla`)) join `apps_rpjepq`.`rpj_mnt_empleado` `e` on(`e`.`emp_correlativo` = `ni`.`nin_id_empleado`)) where `ni`.`nin_tipo_manejo` = 1 group by `ni`.`nin_id_planilla`,`p`.`ppl_numero`,`p`.`ppl_estado_proceso`,`e`.`emp_correlativo`,`e`.`emp_dpi`,`e`.`emp_nombres`,`e`.`emp_apellidos`,`e`.`emp_fecha_ingreso`,`e`.`emp_profesion_oficio`,`ni`.`nin_dias_trabajados`;

-- ============ v_planillas_pensionados ============
CREATE OR REPLACE VIEW v_planillas_pensionados AS
select `p`.`ppl_correlativo` AS `id_planilla`,`p`.`ppl_numero` AS `periodo`,`p`.`ppl_fecha_inicio` AS `ppl_fecha_inicio`,`p`.`ppl_fecha_final` AS `ppl_fecha_final`,`p`.`ppl_fecha_pago` AS `ppl_fecha_pago`,`p`.`ppl_porcentaje_pago` AS `porcentaje`,`p`.`ppl_estado_proceso` AS `estado`,`p`.`ppl_fecha_generacion` AS `ppl_fecha_generacion`,`p`.`ppl_fecha_cierre` AS `ppl_fecha_cierre`,`p`.`ppl_usuario_genera` AS `ppl_usuario_genera`,`p`.`ppl_usuario_cierra` AS `ppl_usuario_cierra`,(select count(0) from `apps_rpjepq`.`rpj_prc_nomina_ingreso` where `apps_rpjepq`.`rpj_prc_nomina_ingreso`.`nin_id_planilla` = `p`.`ppl_correlativo` and `apps_rpjepq`.`rpj_prc_nomina_ingreso`.`nin_tipo_manejo` = 2) AS `total_pensionados`,(select ifnull(sum(`apps_rpjepq`.`rpj_prc_nomina_ingreso`.`nin_valor`),0) from `apps_rpjepq`.`rpj_prc_nomina_ingreso` where `apps_rpjepq`.`rpj_prc_nomina_ingreso`.`nin_id_planilla` = `p`.`ppl_correlativo` and `apps_rpjepq`.`rpj_prc_nomina_ingreso`.`nin_tipo_manejo` = 2) AS `total_ingresos`,(select ifnull(sum(`apps_rpjepq`.`rpj_prc_nomina_descuento`.`nde_valor`),0) from `apps_rpjepq`.`rpj_prc_nomina_descuento` where `apps_rpjepq`.`rpj_prc_nomina_descuento`.`nde_id_planilla` = `p`.`ppl_correlativo` and `apps_rpjepq`.`rpj_prc_nomina_descuento`.`nde_tipo_manejo` = 2) AS `total_descuentos` from `apps_rpjepq`.`rpj_cat_parametro_planilla` `p` where `p`.`ppl_tipo_planilla` = 2 order by `p`.`ppl_numero` desc;

-- ============ v_detalle_nomina_pensionados ============
CREATE OR REPLACE VIEW v_detalle_nomina_pensionados AS
select `ni`.`nin_id_planilla` AS `nin_id_planilla`,`p`.`ppl_numero` AS `planilla`,`p`.`ppl_estado_proceso` AS `estado_planilla`,`j`.`jub_correlativo` AS `id_jubilado`,`j`.`jub_dpi` AS `jub_dpi`,concat(`j`.`jub_nombres`,' ',`j`.`jub_apellidos`) AS `nombre_completo`,`j`.`jub_fecha_jubilacion` AS `jub_fecha_jubilacion`,`ni`.`nin_dias_trabajados` AS `dias_trabajados`,`ni`.`nin_valor_teorico` AS `pension_teorica`,`ni`.`nin_porcentaje_aplicado` AS `porcentaje`,`ni`.`nin_pago_corriente` AS `pago_corriente`,`ni`.`nin_abono_historico` AS `abono_historico`,`apa`.`apa_periodo_deuda` AS `periodo_aplicado`,`ni`.`nin_valor` AS `total_ingreso`,coalesce((select sum(`apps_rpjepq`.`rpj_prc_nomina_descuento`.`nde_valor`) from `apps_rpjepq`.`rpj_prc_nomina_descuento` where `apps_rpjepq`.`rpj_prc_nomina_descuento`.`nde_id_planilla` = `ni`.`nin_id_planilla` and `apps_rpjepq`.`rpj_prc_nomina_descuento`.`nde_id_jubilado` = `ni`.`nin_id_jubilado`),0) AS `total_descuentos`,`ni`.`nin_valor` - coalesce((select sum(`apps_rpjepq`.`rpj_prc_nomina_descuento`.`nde_valor`) from `apps_rpjepq`.`rpj_prc_nomina_descuento` where `apps_rpjepq`.`rpj_prc_nomina_descuento`.`nde_id_planilla` = `ni`.`nin_id_planilla` and `apps_rpjepq`.`rpj_prc_nomina_descuento`.`nde_id_jubilado` = `ni`.`nin_id_jubilado`),0) AS `neto_a_pagar` from (((`apps_rpjepq`.`rpj_prc_nomina_ingreso` `ni` join `apps_rpjepq`.`rpj_cat_parametro_planilla` `p` on(`p`.`ppl_correlativo` = `ni`.`nin_id_planilla`)) join `apps_rpjepq`.`rpj_mnt_jubilado` `j` on(`j`.`jub_correlativo` = `ni`.`nin_id_jubilado`)) left join `apps_rpjepq`.`rpj_prc_aplicacion_pago` `apa` on(`apa`.`apa_id_planilla` = `ni`.`nin_id_planilla` and `apa`.`apa_id_jubilado` = `ni`.`nin_id_jubilado`)) where `ni`.`nin_tipo_manejo` = 2;

-- ============ v_descuentos_nomina_pensionados ============
CREATE OR REPLACE VIEW v_descuentos_nomina_pensionados AS
select `nd`.`nde_id_planilla` AS `nde_id_planilla`,`p`.`ppl_numero` AS `planilla`,`j`.`jub_correlativo` AS `id_jubilado`,concat(`j`.`jub_nombres`,' ',`j`.`jub_apellidos`) AS `nombre_completo`,`td`.`tde_tipo_descuento` AS `tipo_descuento`,`nd`.`nde_valor` AS `monto_descuento` from (((`apps_rpjepq`.`rpj_prc_nomina_descuento` `nd` join `apps_rpjepq`.`rpj_cat_parametro_planilla` `p` on(`p`.`ppl_correlativo` = `nd`.`nde_id_planilla`)) join `apps_rpjepq`.`rpj_mnt_jubilado` `j` on(`j`.`jub_correlativo` = `nd`.`nde_id_jubilado`)) join `apps_rpjepq`.`rpj_cat_tipo_descuento` `td` on(`td`.`tde_id` = `nd`.`nde_tipo_descuento`)) where `nd`.`nde_tipo_manejo` = 2;

-- ============ v_estado_cuenta_pensionado ============
CREATE OR REPLACE VIEW v_estado_cuenta_pensionado AS
select `j`.`jub_correlativo` AS `jub_correlativo`,`j`.`jub_dpi` AS `jub_dpi`,concat(`j`.`jub_nombres`,' ',`j`.`jub_apellidos`) AS `nombre_completo`,`j`.`jub_fecha_jubilacion` AS `jub_fecha_jubilacion`,`j`.`jub_estado` AS `jub_estado`,(select count(0) from `apps_rpjepq`.`rpj_prc_deuda_jubilado` where `apps_rpjepq`.`rpj_prc_deuda_jubilado`.`deu_id_jubilado` = `j`.`jub_correlativo`) AS `meses_total`,(select count(0) from `apps_rpjepq`.`rpj_prc_deuda_jubilado` where `apps_rpjepq`.`rpj_prc_deuda_jubilado`.`deu_id_jubilado` = `j`.`jub_correlativo` and `apps_rpjepq`.`rpj_prc_deuda_jubilado`.`deu_estado` = 'PAGADA') AS `meses_pagados`,(select count(0) from `apps_rpjepq`.`rpj_prc_deuda_jubilado` where `apps_rpjepq`.`rpj_prc_deuda_jubilado`.`deu_id_jubilado` = `j`.`jub_correlativo` and `apps_rpjepq`.`rpj_prc_deuda_jubilado`.`deu_estado` in ('PENDIENTE','PARCIAL')) AS `meses_pendientes`,(select ifnull(sum(`apps_rpjepq`.`rpj_prc_deuda_jubilado`.`deu_monto_pendiente`),0) from `apps_rpjepq`.`rpj_prc_deuda_jubilado` where `apps_rpjepq`.`rpj_prc_deuda_jubilado`.`deu_id_jubilado` = `j`.`jub_correlativo`) AS `deuda_pendiente`,(select ifnull(sum(`apps_rpjepq`.`rpj_prc_deuda_jubilado`.`deu_monto_pagado`),0) from `apps_rpjepq`.`rpj_prc_deuda_jubilado` where `apps_rpjepq`.`rpj_prc_deuda_jubilado`.`deu_id_jubilado` = `j`.`jub_correlativo`) AS `deuda_pagada` from `apps_rpjepq`.`rpj_mnt_jubilado` `j` where `j`.`jub_tipo_manejo` = 2 and `j`.`jub_estado` = 'ACTIVO';

