const { Router } = require("express");
const controller = require("../controllers/salarios.controller");
const authMiddleware = require("../middlewares/auth.middleware");
const { auditAction } = require("../middlewares/audit.middleware");
const { authorizeRoles } = require("../middlewares/role.middleware");
const router = Router();
router.use(authMiddleware);
router.get("/", authorizeRoles("ADMIN", "OPERADOR"), controller.list);
router.get("/:id", authorizeRoles("ADMIN", "OPERADOR"), controller.getById);
router.post("/", authorizeRoles("ADMIN", "OPERADOR"), auditAction("SALARIOS", "CREAR"), controller.create);
router.post("/bulk", authorizeRoles("ADMIN", "OPERADOR"), auditAction("SALARIOS", "CREAR_LOTE"), controller.bulkCreate);
router.put("/:id", authorizeRoles("ADMIN", "OPERADOR"), auditAction("SALARIOS", "EDITAR"), controller.update);
router.delete("/:id", authorizeRoles("ADMIN"), auditAction("SALARIOS", "ELIMINAR"), controller.remove);
module.exports = router;
