const { Router } = require("express");
const controller = require("../controllers/tiempoExtra.controller");
const authMiddleware = require("../middlewares/auth.middleware");
const { auditAction } = require("../middlewares/audit.middleware");
const { authorizeRoles } = require("../middlewares/role.middleware");
const router = Router();
router.use(authMiddleware);
router.get("/", authorizeRoles("ADMIN", "OPERADOR"), controller.list);
router.get("/:id", authorizeRoles("ADMIN", "OPERADOR"), controller.getById);
router.post("/", authorizeRoles("ADMIN", "OPERADOR"), auditAction("TIEMPO_EXTRA", "CREAR"), controller.create);
router.put("/:id", authorizeRoles("ADMIN", "OPERADOR"), auditAction("TIEMPO_EXTRA", "EDITAR"), controller.update);
router.delete("/:id", authorizeRoles("ADMIN"), auditAction("TIEMPO_EXTRA", "ELIMINAR"), controller.remove);
module.exports = router;
